### PR TITLE
Add async method

### PR DESCRIPTION
**Pull request by davej**

### CODE REVIEW

**Comment by silverwind** [comment]
@sindresorhus is the API naming fine with you? It falls a bit out of the scheme with `.async()` unfortunately.

**Comment by sindresorhus** [comment]
Why? I don't see any situation where an async API would be needed.

I guess you opened this because of https://github.com/sindresorhus/shell-path/issues/5, but that begs the question, why would you use this in the renderer?

An explanation of your use-case would be helpful.

**Comment by davej** [comment]
@sindresorhus All of my application logic is in the renderer, I'm only doing UI building in the main/browser process. This is standard for Electron applications (see Atom).

My specific use case is that my app needs to get the Apache/Nginx config files location (I use `apachectl -V`/`nginx -t`) and restart the servers.

**Comment by sindresorhus** [comment]
I'm still unclear why using `fix-path` in the main process is not possible for you? The main process is loaded first, so if you run it there, it applies to the renderer too.

If the only reason you need an async API is to work around https://github.com/sindresorhus/shell-path/issues/5, I'm not really interested in this. You can instead just use your fork until it's fixed in Electron (probably soon, since that method is used by many).

**Comment by davej** [comment]
Ah, you're correct! I didn't realise that main's process.env.PATH was inherited by the renderer.

**Pull request closed without merging**
